### ISSUE TITLE
a = b used as value

### ISSUE THREAD

**Issue by dlsniper** [go-lang-plugin-org/go-lang-idea-plugin#1887]
As an extension of #1577.

```go
package main

func main() {
	a := 1
	b := 2
	if a = b {  // should produce an error: a = b used as value
		println("a = b")
	} else {
		println("a != b")
	}
}
```

**Comment by muly** [comment]
I think it is solved as of now. I ran that code in play.golang.org just now, and I received the error "a = b used as value"

**Comment by dlsniper** [comment]
Hi @muly, the plugin still doesn't report this error so this issue is not resolved yet.

**Comment by dlsniper** [comment]
Fixed in previous PR.
