### ISSUE TITLE
Feature request: commenting out code should also handle imports

### ISSUE THREAD

**Issue by mmindenhall** [go-lang-plugin-org/go-lang-idea-plugin#2006]
Java scenario:

1.  Comment out a line or section of code
1.  Run with code commented out (possible compiler warning complaining about unused imports)
1.  Uncomment code, everything as it was before

Go scenario:

1.  Comment out a line or section of code
1.  If code was only user of an imported package, there's now a compiler error
1.  Comment out the unused imports
1.  Run with code commented out
1.  Uncomment code
1.  Uncomment imports

Preferred Go scenario:

1.  Comment out a line or section of code
1.  **IDE detects that this results in unused import(s), comments out as well**
1.  Run with code commented out
1.  Uncomment code
1.  **IDE detects that this results in "Unresolved reference" errors, uncomments any imports that match the unresolved reference names.**

This behavior should be an option that is disabled by default, as some developers might object to this feature due to the following:

1.  A block of code gets commented out, and results in one or more imports also being commented out
1.  The block of code gets deleted without uncommenting
1.  Now there are unused, but commented out import statements in the file

Of course, it might be possible to do this in a way that's better than what I described.  For example:

1.  Comment out a line or section of code
1.  IDE detects which lines result in "Unused import" errors, keeps track of those imports, and removes them automatically.
1.  Uncomment the code
1.  IDE knows which lines need to have imports restored, restores the imports

**Comment by ignatov** [comment]
@zolotov Comment action may trigger an uptimize imports action, right?

**Comment by zolotov** [comment]
@ignatov I think so

**Comment by mmindenhall** [comment]
It's more complicated than that.  Comment action triggering optimize imports action would take care of "Unused imports" errors, but then uncommenting the code would result in "Unresolved reference" errors that would need to be manually resolved.  

For example, consider this code snippet:

```go
import (
	// some imports
	log "github.com/cihub/seelog"
	// more imports
)

func doStuff() {
	doSomething()

	doSomethingElse()
	log.Debug("did something else")
}
```
Now:

1.  I use `Cmd-/` to comment out the last two lines of `doStuff`:
    ```go
    //	doSomethingElse()
    //	log.Debug("did something else")

    ```
1. This triggers optimize import action, removing the `log` import
1.  I run, test, or whatever with code commented out
1.  I uncomment code (again with `Cmd-/`)
1.  Now there's an "Unresolved reference" error.  The IDE will recommend the `log` stdlib package, whereas I want to restore my previous alias.

Hence, I think you would need to just comment out the imports (so they can be restored), or keep track of which imports were removed (so they can be unambiguously restored).

**Comment by zolotov** [comment]
> but then uncommenting the code would result in "Unresolved reference" errors that would need to be manually resolved.

After uncommenting all missing imports will be added automatically or via alt+enter depending on your settings. I don't see any reasons to process unommenting action like you suggested.

**Comment by mistbow-git** [comment]
I think so good idea comment an uncomment import!)
+1

**Comment by mdwhatcott** [comment]
I would prefer that the editor just delete unused imports rather than comment them out. I agree with @zolotov that the IDE can help you re-resolve the imports with alt+enter after uncommenting the code.

**Comment by mistbow-git** [comment]
I think the IDE must delete import when I delete a line, and comment if I comment line... When I remove comment IDE must uncomment import. Alt+Enter not going idea. :(

**Comment by mmindenhall** [comment]
@zolotov, @mdwhatcott,

How can the IDE re-resolve an aliased import?  If you have a way to solve that (e.g., by keeping track of previously used aliases), then it sounds fine to do it the way you suggest.

So in the example in my previous comment, after I uncomment the code, I would expect alt+enter to suggest my previous alias along with any other `log` packages in the path.

I think I'll file that one as a separate feature request, because it has usefulness beyond this scope.

**Comment by mmindenhall** [comment]
Done.  See #2007.

**Comment by zolotov** [comment]
@mmindenhall 

> How can the IDE re-resolve an aliased import? 

It won't. I still don't see the point of all of these. It looks like quite complicated and ambiguously feature for very rare scenarios. In common case it can resolve import or undo (cmd+z) comment action.

**Comment by mdwhatcott** [comment]
@mmindenhall, @mistbow-git - So, would deleting a commented out line cause the commented out import statement to be deleted? If not, the imports section is bound to become cluttered and messy.

**Comment by mmindenhall** [comment]
@mdwhatcott, I submitted #2007 as a result of this thread.  If the IDE can keep track of aliases, then IMHO the following would be acceptable:

1.  Comment out code with cmd-/.
1.  That triggers optimize imports, which **removes** resulting unused imports
1.  Uncomment code, and re-resolve imports with alt+enter (as you and @zolotov initially suggested, except now per #2007 the IDE will suggest known aliases as well as known packages).
