### ISSUE TITLE
Inconsistent breaking on breakpoint in Windows 10

### ISSUE THREAD

**Issue by asampal** [go-lang-plugin-org/go-lang-idea-plugin#2487]
#- Plugin version (or commit hash): go-lang-plugin 0.11.1326, delve 60946a759c03e68520b4e223cea9f79259612a21
- IDE name and version: IntelliJ Idea 2016.1.1
- Java version:  1.8.0_77-b03
- OS name and version: Windows 10 64 bit

- What are you trying to do?

Stop at breakpoint
- What would you expect to happen?

Debugger starts and stops at breakpoint.
- What happens?

Most of the time the program runs to finish. Sometimes it stops at the breakpoint (maybe 1/10 times?). The pattern of running/stopping doesn't seem deterministic. Sometimes two or three consecutive runs will stop, other times I could run 15 times without stopping.

```go
package main

import (
	"fmt"
	"math/rand"
	"sync"
	"time"
)

func main() {
	rand.Seed(time.Now().UnixNano())
	wg := sync.WaitGroup{}
	for x := 1; x <= 5; x++ {
		wg.Add(1)
		go func(a int) {
			defer wg.Done()
			time.Sleep(time.Second * time.Duration(rand.Intn(3)))
			fmt.Println("I'm done: ", a)
		}(x)
	}
	wg.Wait()
}
```

![inconsistent-breaking](https://cloud.githubusercontent.com/assets/281639/14759137/8dcede6c-08e5-11e6-91db-b8889b216df5.gif)

**Comment by dlsniper** [comment]
Hi, thanks for the ticket. Can you please also attach the logs for this? If you are not sure where to get them let me know. I suspect something might be up with delve not the plugin but lets see. Thanks.

**Comment by dlsniper** [comment]
Also, you mentioned a commit hash for delve. Are you using a custom version of delve (changed something to how IDEA starts/in the settings) or none of these things? I ask because the plugin comes with delve built in.

**Comment by asampal** [comment]
I've attached the log showing a few runs of the application. This time the debugger seemed to mostly stop. I think it was something like 2 times stopped, 1 didn't, 3 times stopped, 1 didn't.

WRT delve, I have an entry, `dlv.path=d:/dev/projects/_go/bin/dlv.exe`, in idea.properties to point to a delve I sometimes build myself and it installs under GOPATH/bin. The problem with not always stopping on breakpoints happens with the delve you bundle with the plugin, as well. I haven't changed anything that I can recall which would affect how Idea starts other than the VM memory settings.

One possibly related note is that yesterday when I reported this issue, I was using the default Idea settings for the heap, 128m start and 768m max. I normally use higher values than these and for the runs you see in the log, I had set starting heap to 1024m and max to 2048m. I'm not sure if the intermittent stopping is related to memory use, but with the default settings it seemed that the debugger mostly didn't stop. For the runs with more memory allocated, it seemed to mostly stop.

**Comment by mahdiz** [comment]
I have exactly the same problem in Windows 10 64-bit plugin version 0.11.1295. I'm attaching my idea-log file as well. The debugger didn't stop at the breakpoint the first two attempts but stopped at the third time. @dlsniper please search for "RPCServer.Detach" in the log file: it seems that every time the debugger doesn't stop at breakpoint, the RPC server is suddenly detached. This happens in @asampal's log file as well.

[idea-log.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/239136/idea-log.txt)

**Comment by dlsniper** [comment]
@mahdiz that's a known problem, see https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2360

As for the problem reported by @asampal I haven't had a chance to look at it yes, sorry, #2360 keeps me busy (aside from work and life).

**Comment by kolkov** [comment]
+1 the same problem.

**Comment by asampal** [comment]
@dlsniper are you saying that this issue is likely a dupe of #2360 ?

**Comment by dlsniper** [comment]
@asampal I haven't had a chance to look in the log from you. But for @mahdiz either running or not is a dupe of #2360 for sure.
If the debugging stops working unexpected then it's a problem somewhere, either in the app (crashes), either in (delve gets something wrong) or in the plugin.

**Comment by kolkov** [comment]
![image](https://cloud.githubusercontent.com/assets/3740898/14863929/67fe31fe-0cc0-11e6-9714-784055419d50.png)

**Comment by dlsniper** [comment]
@kolkov that looks exactly like #2360.

**Comment by kolkov** [comment]
@dlsniper ok. I can not write at 2360.

**Comment by dlsniper** [comment]
@kolkov there's a reason you can't write to that. Please read the conversation.

**Comment by kolkov** [comment]
[idea.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/239192/idea.txt)

**Comment by MikeGCV** [comment]
Happening to also in windows 10 x64 and ubuntu 16.04. Using Intellij community version

**Comment by dlsniper** [comment]
@MikeGCV please provide a log file. If you don't know how then I can guide you thru. Thanks.

**Comment by MikeGCV** [comment]
Here's the log
[Log.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/244068/Log.txt)
Hope it helps

**Comment by dlsniper** [comment]
@MikeGCV unfortunately you've truncated too much from the log, there should be more lines with `com.goide.dlv.DlvVm - IN` not just the one that you have.

**Comment by kolkov** [comment]
+1

**Comment by MikeGCV** [comment]
sorry about that, make another one

**Comment by dlsniper** [comment]
@MikeGCV thanks, I think this is a bit different than what @asampal experiences and it doesn't seem to fit into #2360 either (at least for one of the run cases, the other one is the #2360 one). Can you please open up a separate issue and give some more details there? Also if the code to reproduce this is open-source it would be perfect to have it. Thanks

**Comment by MikeGCV** [comment]
ok, a can't show the original code, but i have made a new one withe the same behavior. I will open a separate issue. Thank you

**Comment by dlsniper** [comment]
@MikeGCV please make sure to attach the logs as well for the new one. Unfortunately #2360 make it hard to distinctly separate issues.

**Comment by MikeGCV** [comment]
Done, issue #2500

**Comment by MikeGCV** [comment]
I must say, with this last build, of the plugin 0.11.1343, after a few retry's , the debug works again

**Comment by dlsniper** [comment]
Nothing has changed with the debugger since a long time, the issue is still there, it's just the randomness of it which makes it appear like that.

**Comment by MikeGCV** [comment]
Ok

**Comment by kolkov** [comment]
[idea_log.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/246795/idea_log.txt)
I think that is the same problem.

**Comment by kolkov** [comment]
In 15.0.5 all works correctly.

**Comment by dlsniper** [comment]
@kolkov what plugin version oo you have in 15.0.5?

**Comment by kolkov** [comment]
0.10.1298. last available

**Comment by dlsniper** [comment]
I've just had a look at it, you've experienced a false positive.

Your issue is deep inside how delve works. Please see https://github.com/derekparker/delve/issues/523 for reference. If you want to fix this, please direct your efforts there as they would be much better spent. There was a PR attempting to fix it: https://github.com/derekparker/delve/pull/520 but unfortunately it creates a different set of problems, follow the discussion there.

Thank you!

**Comment by kolkov** [comment]
Debugging still does not work... ((( @dlsniper

**Comment by dlsniper** [comment]
@kolkov unfortunately I was just investigating this issue to make it easier to determine where the problem is. @zolotov filed the issue on Delve, where this issue happens and as you can see, the problem is hard to solve.
Please either suggest a fix for this in Delve, which is written in Go and it's not even in the OS debugging part (the hard one) but in the networking interaction layer, in the plugin or wait for someone else to fix it.
I appreciate this is an important issue for you and a lot of other issues but also please remember this (and Delve I think) is an open-source project done in the spare time of the contributors so just complaining about it doesn't necessarily lead to a solution quicker.

Thank you for your understanding and patience.

**Comment by dlsniper** [comment]
@kolkov and others, there's a potential fix here: https://github.com/derekparker/delve/pull/578 Please help testing it out. If you need help with how to use this version instead of the one shipped with the plugin, please let me know. Thank you.

**Comment by dlsniper** [comment]
fixed in #2599
