### ISSUE TITLE
Debug only works in the first try

### ISSUE THREAD

**Issue by MikeGCV** [go-lang-plugin-org/go-lang-idea-plugin#2500]
- Plugin version (or commit hash): 0.11.1343
- IDE name and version: IntelliJ IDEA 2016.1 CE #IC-145.970
- Java version: JRE 1.8.74 amd64

- OS name and version: 
Windodws 8.1 x64
- What are you trying to do?
Debug a Go program
- What would you expect to happen?
Debug working on all reloads
- What happens?
Debug only works the firs time it's called

On cold boot and first debug, all works fine, here's the log:
[Cold Boot first Debug log.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/244840/Cold.Boot.first.Debug.log.txt)

On reloading the debug, it doesn't work, here's the log;
[Reload Debug.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/244844/Reload.Debug.txt)

Total log is here:
[Total log.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/244848/Total.log.txt)

The Go code:
[main.go.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/244853/main.go.txt)

Thank you

**Comment by dlsniper** [comment]
Hi, please include the full log here, I think you've truncated the log too much in the `total log.txt`. You might want to anonymize any information that could be private from it (such as paths or dirs) so make sure you do so if needed. Thanks.

**Comment by MikeGCV** [comment]
Complete one
[Total log.txt](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/files/244959/Total.log.txt)

**Comment by prsolucoes** [comment]
Same problem. Debug stop work.

**Comment by dlsniper** [comment]
Same request, please provide logs, reproducible code steps to do it. Otherwise it's hard to tell what the issue is and the report is just noise (you'd think it's a known issue since others reported it and we said the issue is in delve, not the plugin). Thank you.

**Comment by ignatov** [comment]
@zolotov is it the same issue in Delve has been already fixed by you?

**Comment by zolotov** [comment]
@ignatov yes but the pr is not accepted, see related issue https://github.com/derekparker/delve/issues/523

**Comment by gavin-hu** [comment]
Same problem under Mac OS X

IntelliJ IDEA 2016.1.2
Build #IC-145.972, built on May 14, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by chriscannon** [comment]
I have same issue, but I cannot reliably reproduce it. However, when it does actually debug and stop at a breakpoint, it only works on the first run. Here's my current configuration:

Mac OSX 10.11.4
IntelliJ IDEA 2016.1.2
Build #IU-145.972, built on May 14, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Delve Debugger
Version: 0.11.0-alpha (I checked out this exact tag from the repo)
Build: 6774a6c782b2f321bed46b32af45a882d55287ad

**Comment by dlsniper** [comment]
@gavin-hu, @chriscannon please see the delve linked just issue above. It's a known issue in delve. Please have some patience until the best course of action is determined for this as it's a fairly complex one.

**Comment by johnnadratowski** [comment]
@dlsniper - It seems from the comments on the Delve PR that the fix needs to be done in the golang plugin, no?  I might be misunderstanding the conversation, but it seemed to me they were saying the client is supposed to handle that synchronization.

**Comment by dlsniper** [comment]
@johnnadratowski it's either the client or the server which needs to handle this. Normally this shouldn't happen in the client as the server should be responsible for this. However I can't make a comment into where the change should happen, I'll let this in the more capable hands of @ignatov and @zolotov to judge and decide.

**Comment by zolotov** [comment]
@johnnadratowski we absolutely sure that it should be handled by server but since it requires full reimplementation of server-side and likely it won't be fixed in the nearest future, we're going to fix it in our particular client. Not sure about estimations yet.

**Comment by johnnadratowski** [comment]
@zolotov - makes sense, thanks guys. Love the project!

**Comment by rachoac** [comment]
What's the best way to get back to a stable version of the plugin, where this bug doesn't exist? its quite deterimental to my workflow...

**Comment by ronbarab** [comment]
@rachoac did you managed to work your way around this? please let me know if there's a version of the plugin which i can use without this issue..
Thanks

**Comment by kolkov** [comment]
@zolotov @ignatov не, ребят... совсем все плохо стало с отладкой. Так не пойдет, нужно что-то срочно делать... ((( вместо работы только и сидишь в попытках хоть как-то его запустить, можно и 15 минут так просидеть! ((( может есть хоть какое-то временное решение, которое на ветке delve предлагали? Или уж откатываться на 15 версию?

**Comment by kolkov** [comment]
@ronbarab 0.10.1298 work fine! But for UDEA 15.0.5 only. (

**Comment by zolotov** [comment]
@kolkov there are couple options:

1. if 0.10.1298 really works then you can try to use `dlv` binary file from it. Find it in plugins directory (https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs)
2. you can try to build a plugin with this change made by @dlsniper: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2488/files. The change doesn't fix anything but might make life easier in theory. To build the plugin clone repo, run `./gradlew buildPlugin`, find plugin dist in `./distributions` and install it from disk.

**Comment by zolotov** [comment]
And do follow the original issue: https://github.com/derekparker/delve/issues/523#issuecomment-222378220

**Comment by dlsniper** [comment]
@kolkov 0.10.1298 has the same issue, for some reason it might happen that the IDE is slower or who knows what else happens there but I could reproduce the issue with that IDE/plugin version. Like @zolotov said, my "fix" is a workaround and not good enough to make it to the plugin. It would be preferable to have delve fix this (and this is Go code, you could help). I don't have enough time to contribute to the plugin these days, let alone to delve, so please, try and help delve fixing it! Thank you!

**Comment by kolkov** [comment]
@zolotov If I use old dlv.exe from 0.10.1298 all working fine for 2016.2EAP in 100% cases.
@dlsniper Thanks! Next time I will try to build and test this fixed version.)

**Comment by MichaelMure** [comment]
I tested the delve branch https://github.com/derekparker/delve/pull/578 and it does work ! No more debugger hanging \o/

**Comment by dlsniper** [comment]
@MichaelMure thanks for testing, please report it to Delve as well!

**Comment by dlsniper** [comment]
fixed in #2599

**Comment by Enmk** [comment]
Hi guys! It is 2018 and I still experience this very issue with GoLand 2018.2.4 on both MacOS and Linux. And it is annoying as heck!

**Comment by dlsniper** [comment]
@enmk please open an issue on https://youtrack.jetbrains.com/issues/Go and provide additional information on how to reproduce this issue. Does it happen in any application? Do you have a sample application to reproduce it? Please attach the logs from Help | Compress Logs and Show in... and maybe we can notice the issue there.

Also, this project has been abandoned for the last 2.5 years so if you need official JetBrains suport, the issue tracker above is where you need to go.
